spring:
  application:
      name: "wind-blog"

  resources:
    static-locations: classpath:/webapp/static/

#    static-locations: file:/Users/qianchun/wind/wind-blog/src/main/resources/webapp/static/


  thymeleaf:
    prefix: classpath:/webapp/view/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    check-template-location: false

#  mvc:
#    view:
#      prefix: /WEB-INF/view/ # 页面默认前缀目录
#      suffix: .jsp # 响应页面默认后缀

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: redis
    port: 6379
    password: wind
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接

#  datasource:
#    url: jdbc:mysql://mysql:3306/wind_auth?useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: root
#    password: Dev123@wind.COM
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    initialize: false
server:
  port: 8099