spring:
  application:
      name: "wind-blog"

#  data:
#    elasticsearch:
#      cluster-nodes: elasticsearch:9200

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: redis
    port: 6379
    password: wind
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  # publisher-confirms: true
    virtual-host: /

  datasource:
    url: jdbc:mysql://mysql:3306/wind_blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: Dev123@wind.COM
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080